macro(add_targets)

# given: APP_TARGETS

set(TARGET_INFO "")
foreach(ITEM ${APP_TARGETS})
    set(TARGET_INFO "${TARGET_INFO}" "${ITEM}")
    list(LENGTH TARGET_INFO ITEM_LENGTH)
    if(ITEM_LENGTH EQUAL 3)
        list(GET TARGET_INFO 1 TEXT_NAME)
        list(GET TARGET_INFO 2 DIR_NAME)
        if(NOT APP_TARGET_TOTAL_NUMBER)
            set(APP_TARGET_TOTAL_NUMBER 0)
        endif()
        if(EXISTS "${APP_SOURCE_DIR}/targets/${DIR_NAME}")
            set(APP_TARGET_IDS ${APP_TARGET_IDS} ${APP_TARGET_TOTAL_NUMBER})
            math(EXPR APP_TARGET_TOTAL_NUMBER "${APP_TARGET_TOTAL_NUMBER}+1")
            set(APP_TARGET_TEXT_NAMES ${APP_TARGET_TEXT_NAMES} ${TEXT_NAME})
            set(APP_TARGET_DIR_NAMES ${APP_TARGET_DIR_NAMES} ${DIR_NAME})
        endif()
        set(TARGET_INFO "")
    endif()
endforeach()
if(APP_TARGET_TOTAL_NUMBER GREATER 0)
    message(STATUS ${STRING_REPEAT_MINUS_80})
    message(STATUS "Found Targets")
    message(STATUS "    APP_TARGET_TOTAL_NUMBER = ${APP_TARGET_TOTAL_NUMBER}")
    message(STATUS "    APP_TARGET_IDS = ${APP_TARGET_IDS}")
    message(STATUS "    APP_TARGET_TEXT_NAMES = ${APP_TARGET_TEXT_NAMES}")
    message(STATUS "    APP_TARGET_DIR_NAMES = ${APP_TARGET_DIR_NAMES}")
    message(STATUS ${STRING_REPEAT_MINUS_80})
endif()

endmacro()